[build]
  publish = "dist"
  command = "node scripts/build-with-ssg.js"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  # Do NOT set public Supabase keys directly here for secrets scan compliance
  # VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set ONLY in the Netlify dashboard for production

# Execute pre-rendering during build
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Single simple redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https://meowrescue.windsurf.build https://sfrlnidbiviniuqhryyc.supabase.co https://images.unsplash.com *; connect-src 'self' https://sfrlnidbiviniuqhryyc.supabase.co wss://sfrlnidbiviniuqhryyc.supabase.co; frame-src 'self' https://sfrlnidbiviniuqhryyc.supabase.co https:; object-src 'none'"

# Add specific headers for assets
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify secrets scanning allowlist for public Supabase keys
[secrets_scan]
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]
  omit_paths = ["dist/assets/main.js", "dist/server/assets/entry-server.js"]
