[build]
  publish = "dist"
  command = "node scripts/netlify-build.js"

  # Environment configuration
  [build.environment]
    NODE_VERSION = "18.18.0"
    NPM_VERSION = "9.8.1"
    # These must be set in Netlify dashboard
    VITE_SUPABASE_URL = ""
    VITE_SUPABASE_ANON_KEY = ""
    # Disable unused languages to speed up build
    RUBY_VERSION = ""
    PYTHON_VERSION = ""
    PHP_VERSION = ""
    GO_VERSION = ""
    # Do NOT set public Supabase keys directly here for secrets scan compliance
    # VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set ONLY in the Netlify dashboard for production

  # Cache configuration
  [build.cache]
    restore = true
    save = true
    
    # Only cache these specific directories
    directories = [
      "node_modules",
      ".vite",
      ".cache"
    ]
    
    # Clear cache when these files change
    files = [
      "package.json",
      "package-lock.json",
      "tsconfig.json",
      "vite.config.ts"
    ]

# Execute pre-rendering during build
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Single simple redirect rule for SPA
# Handle SPA navigation with more specific rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  query = true

# Handle specific static files
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https://meowrescue.windsurf.build https://sfrlnidbiviniuqhryyc.supabase.co https://images.unsplash.com *; connect-src 'self' https://sfrlnidbiviniuqhryyc.supabase.co wss://sfrlnidbiviniuqhryyc.supabase.co; frame-src 'self' https:; object-src 'none'"

# Add specific headers for assets
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify secrets scanning allowlist for public Supabase keys
[secrets_scan]
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]
  omit_paths = ["dist/assets/main.js", "dist/server/assets/entry-server.js"]
