
/**
 * This script extracts route information from routes.tsx and creates a JavaScript 
 * version that can be used during the build process
 */
const fs = require('fs');
const path = require('path');

// This is a simplified version that will run at build time
// to ensure our build scripts can access route information
function generateRoutesCompat() {
  try {
    console.log('Generating routes compatibility layer...');
    
    // Read the routes.tsx file
    const routesPath = path.resolve(__dirname, '../src/routes.tsx');
    const routesContent = fs.readFileSync(routesPath, 'utf-8');
    
    // Extract the staticPaths array using regex
    const pathsMatch = routesContent.match(/getStaticPaths.*?return\s*\[([\s\S]*?)\];/);
    
    if (!pathsMatch || !pathsMatch[1]) {
      console.warn('Could not extract static paths from routes.tsx, using default paths');
      // Use default paths
      const defaultPaths = [
        "'/'",
        "'/about'",
        "'/cats'",
        "'/adopt'",
        "'/adopt/apply'",
        "'/blog'",
        "'/events'",
        "'/resources'",
        "'/contact'",
        "'/donate'",
        "'/volunteer'",
        "'/volunteer/apply'",
        "'/foster'",
        "'/foster/apply'",
        "'/login'",
        "'/register'",
        "'/reset-password'",
        "'/privacy-policy'",
        "'/terms-of-service'",
        "'/lost-found'",
        "'/404'",
      ].join(',\n    ');
      
      writeRoutesJs(defaultPaths);
      return;
    }
    
    const pathsContent = pathsMatch[1].trim();
    writeRoutesJs(pathsContent);
  } catch (error) {
    console.error('Error generating routes compatibility layer:', error);
    process.exit(1);
  }
}

function writeRoutesJs(pathsContent) {
  // Create a routes.js file that exports the paths in ESM format
  const jsContent = `
// This file is auto-generated by scripts/build-routes.js
// Do not edit directly

// Routes data extracted from routes.tsx
export const staticPaths = [${pathsContent}];

// Simplified route objects for build scripts
export const routes = staticPaths.map(path => ({ path }));

export function getStaticPaths() {
  return staticPaths;
}

export function fetchAllCatIds() {
  return ['cat1', 'cat2', 'cat3']; // Simplified for build time
}

export function fetchAllBlogSlugs() {
  return ['post1', 'post2', 'post3']; // Simplified for build time
}

export function fetchAllEventIds() {
  return ['event1', 'event2', 'event3']; // Simplified for build time
}
`;
  
  fs.writeFileSync(path.resolve(__dirname, '../src/routes.js'), jsContent);
  console.log('Routes compatibility layer generated successfully');
}

generateRoutesCompat();
